### ISSUE TITLE
invalid plugin: eedi2cuda

### ISSUE THREAD

**Issue by hooke007** [AmusementClub/tools#1]

**Comment by AkarinVS** [comment]
This is intentional. Due to some unfortunate events, eedi2cuda is unmaintained now. As we have strict policies on cuda plugins compatibilities, we have to phase out eedi2cuda.

If you want, you could replace the bundled dummy `eedi2cuda.dll` with the one you have, but we can't guarantee the compatibility with the rest of bundled plugins.
